import type { NextPage } from "next"
import useTranslation from "next-translate/useTranslation"
import Head from "next/head"
import { useState } from "react"
import styled from "styled-components"
import Boat from "../components/Boat/Boat"
import Clicker from "../components/Clicker/Game"
import Zone from "../components/Clicker/Zone"
import ClientOnly from "../components/ClientOnly"
import Crew from "../components/Crew/Crew"
import CurrenciesList from "../components/Currencies/CurrenciesList"
import Navigation from "../components/Global/Navigation"
import Goals from "../components/Goals/Goals"
import StatsList from "../components/Stats/StatsList"
import { CloseTutorialButton, Column, Container, Header, Logo, Row, TutorialClassNames, TutorialContainer } from "../components/styled/Globals"
import { possibleGems } from "../lib/data/treasureGame"
import { zones } from "../lib/data/zones"
import { EInstance } from "../lib/enums"
import { ActionEnum, useGameState } from "../lib/hooks/GameContext"
import { useTutorial } from "../lib/hooks/TutorialContext"
import useCards from "../lib/hooks/useCards"
import useInstance from "../lib/hooks/useInstance"
import useSave from "../lib/hooks/useSave"
import tutorialSteps from "../lib/data/tutorial"

const AdminButton = styled.a`
  display: block;
  border-radius: 99px;
  text-align: center;
  font-weight: bold;
  font-size: 0.8em;
  padding: 5px;
  background: white;
  margin-top: 15px;
  cursor: pointer;
  font-family: "Open Sans";
`

const Home: NextPage = () => {
  const { instance, changeInstance } = useInstance()
  // const [paused, setPaused] = useState(false)
  const gameState = useGameState()
  const [save] = useSave()
  const tutorial = useTutorial()
  const { t } = useTranslation()

  const zoneId = gameState.state.currentZone

  return (
    <>
      <Navigation />
      {/* <TutorialModal /> */}
      <TutorialContainer
        active={tutorial.step !== undefined && tutorial.state.showModal && !tutorial.step?.isInModal}
        isInModal={tutorial.step !== undefined && tutorial.step?.isInModal}
      >
        <CloseTutorialButton onClick={() => tutorial.dispatch.setHideTutorial(true)}>{t("tutorial:closeTutorial")}</CloseTutorialButton>
      </TutorialContainer>

      <Container>
        <Head>
          <title>One Piece Clicker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ClientOnly>
          <TutorialClassNames active={tutorial.step !== undefined && tutorial.state.showModal && !tutorial.state.hideTutorial}>
            <Header>
              <Row>
                <Column span={5.75} xs={24} sm={24} md={24}>
                  <Logo src="images/logo.png" />
                </Column>
                <Column span={18.25} xs={24} sm={24} md={24}>
                  <CurrenciesList />
                </Column>
              </Row>
            </Header>
            <Row gutter={[16, 16]}>
              <Column span={17} sm={24} md={15} lg={16}>
                <Row gutter={[16, 16]}>
                  <Column position={0} span={8} sm={24} mdPosition={2} smPosition={2} md={24} lg={24}>
                    <Row>
                      <Column span={24} lg={12} md={12} sm={12}>
                        <StatsList />
                      </Column>
                      <Column span={24} lg={12} md={12} sm={12}>
                        <Goals />
                      </Column>
                    </Row>
                  </Column>
                  <Column span={16} sm={24} md={24} lg={24}>
                    {instance == EInstance.Zone && <Zone zone={zones[zoneId]} />}
                    {(instance == EInstance.Clicker || instance == EInstance.Dungeon) && <Clicker zoneId={zoneId} paused={false} debug={false} />}
                  </Column>
                </Row>
                <Row gutter={[16, 16]}>
                  <Column span={24}>
                    <Boat />
                  </Column>
                </Row>
              </Column>
              <Column span={7} sm={24} md={9} lg={8}>
                {/* <ItemList /> */}

                <Crew />
              </Column>
            </Row>
          </TutorialClassNames>
        </ClientOnly>
      </Container>
    </>
  )
}

export default Home
