import type { NextPage } from "next"
import Head from "next/head"
import { Container } from "../components/styled/Globals"
import styled from "styled-components"
import "antd/dist/antd.css"
import { getThumbImageSrc, intWithSpaces } from "../lib/clickerFunctions"
import { TUnit } from "../lib/types"
import { useState } from "react"
import Table, { TColumn } from "../components/Global/Table"
import ClientOnly from "../components/ClientOnly"
const dataSource: TUnit[] = require("../lib/units.json")

export const columns: TColumn<TUnit>[] = [
  {
    label: "",
    dataKey: "img",
    key: "img",
    render: (record, text) => <img src={getThumbImageSrc(record.id)} />,
    sortMode: false,
  },
  {
    label: "#",
    dataKey: "id",
    key: "id",
    sortMode: true,
  },

  {
    label: "Name",
    dataKey: "name",
    key: "name",
    sortMode: "string",
  },
  {
    label: "Cost.",
    dataKey: "cost",
    key: "cost",
    sortMode: "number",
  },
  {
    label: "Rarity.",
    dataKey: "stars",
    key: "stars",
    sortMode: "number",
  },
  {
    label: "HP",
    dataKey: "HPLvlMax",
    key: "HPLvlMax",
    sortMode: "number",
  },
  {
    label: "ATK",
    dataKey: "ATKLvlMax",
    key: "ATKLvlMax",
    sortMode: "number",
  },
  {
    label: "Price",
    dataKey: "price",
    key: "price",
    render: (record, _) => {
      const { HPLvlMax, ATKLvl1, cost, stars, maxLvl } = record
      const price = (ATKLvl1 + HPLvlMax) * maxLvl * cost * stars * 10
      return intWithSpaces(price) + " $"
    },
    sort: (a, b) => {
      const priceA = (a.ATKLvl1 + a.HPLvlMax) * a.maxLvl * a.cost * a.stars * 10
      const priceB = (b.ATKLvl1 + b.HPLvlMax) * b.maxLvl * b.cost * b.stars * 10
      return priceA - priceB
    },
  },
]

const UnitTablePage: NextPage = () => {
  const data = dataSource.splice(0, 50)
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet" />
      </Head>
      <h2 style={{ color: "white" }}>Table</h2>
      <ClientOnly>
        <Table style={{ minWidth: "70vw", fontSize: "1.2rem", fontFamily: "Courier New, Courier, monospace" }} data={data} columns={columns} />
      </ClientOnly>
    </Container>
  )
}

export default UnitTablePage
