import type { NextPage } from "next"
import Head from "next/head"
import { Container } from "../components/styled/Globals"
import styled from "styled-components"
import "antd/dist/antd.css"
import { getThumbImageSrc, intWithSpaces } from "../lib/clickerFunctions"
import { TUnit } from "../lib/types"
import { useState } from "react"
import Table, { TColumn } from "../components/Global/Table"
import ClientOnly from "../components/ClientOnly"
import { GameProvider } from "../lib/hooks/GameContext"
import TestComponent from "../components/TestComponent"
import { ReactNotifications } from "react-notifications-component"

const UnitTablePage: NextPage = () => {
  return (
    <>
      <ReactNotifications className="classic-font" />
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2 style={{ color: "white" }}>Test Context</h2>
        <ClientOnly>
          <GameProvider>
            <TestComponent />
          </GameProvider>
        </ClientOnly>
      </Container>
    </>
  )
}

export default UnitTablePage
