import type { NextPage } from "next"
import Head from "next/head"
import { Container } from "../components/styled/Globals"
import ClientOnly from "../components/ClientOnly"
import styled from "styled-components"
import TreasureFinder from "../components/TreasureGame/TreasureFinderUsingContext"
import { TreasureGameProvider } from "../lib/hooks/TreasureGameContext"

const TreasureFinderPage: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ClientOnly>
        <h2>TreasureFinder !</h2>
        <TreasureGameProvider>
          <TreasureFinder />
        </TreasureGameProvider>
      </ClientOnly>
    </Container>
  )
}

export default TreasureFinderPage
